version: '2.4'
services:
    postgres:
        image: postgres:13-alpine
        container_name: postgres 
        restart: always
        environment:
            - POSTGRES_PASSWORD=@B50lut3
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
            - PGDATA=/postgresql/data
        volumes:
            - ./pg_db:/postgresql/data
            - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
        ports:
            - '5432:5432'
    go:
        image: golang:1.15
        container_name: golang 
        restart: always
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        network_mode: host
        depends_on:
            - postgres
        command: /bin/sh
        stdin_open: true
        tty: true

volumes: 
    db: